### ISSUE TITLE
Svelte PackingInfiniteGrid - overflowing item content

### ISSUE THREAD

**Issue by FluffyDiscord** [naver/egjs-infinitegrid#524] opened 2022-11-02 21:44 UTC
## Description
For some reason item sizes are always wrong no matter the container size and things overflow. In fact every grid solution seems broken. What am I doing wrong ?

![obrazek](https://user-images.githubusercontent.com/10332247/199607787-90d008a8-80ce-449a-9855-38b0fcac3edb.png)
![obrazek](https://user-images.githubusercontent.com/10332247/199607840-6b83a7ae-acaf-43b2-b09c-0ad774a049a9.png)

## Steps to check or reproduce

- try to render things (?)

```html
<script lang="ts">
    import { PackingInfiniteGrid } from "@egjs/svelte-infinitegrid"
    import axiosClient from "@utils/AxiosClient"

    export let route: string
    export let page = 0
    let items = []

    const handleAppend = ({ detail: e }) => {
        e.wait()

        axiosClient.get(route+"/"+page).then(response => {
            if(Array.isArray(response.data) && response.data.length > 0) {
                e.ready()

                items = [...items, ...response.data]
                page++
            }
        })
    }
</script>

<PackingInfiniteGrid
        gap={30}
        align="stretch"
        {items}
        on:requestAppend={handleAppend}
        let:visibleItems
>
    {#each visibleItems as item (item.key)}
        <a href="#" class="flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100">
            {#if item.data.file.isImage}
                <img class="w-full rounded-t-lg h-20 md:rounded-none md:rounded-l-lg object-cover md:h-full md:w-44 mr-5"
                     src="{item.data.file.preview}"
                     alt="{item.data.file.name}"
                />
            {:else}
                <img class="w-full rounded-t-lg md:h-auto md:rounded-none md:rounded-l-lg object-cover md:w-20 mx-6"
                     src="{item.data.file.preview}"
                     alt="{item.data.file.name}"
                />
            {/if}
            <div class="flex flex-col justify-between p-6 leading-normal">
                <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900">
                    {item.data.name}
                </h5>
                {#if item.data.annotation}
                    <div class="mb-3">
                        {item.data.annotation}
                    </div>
                {/if}
            </div>
        </a>
    {/each}
</PackingInfiniteGrid>
```

**Comment by malangfox** [comment] 2022-11-07 01:34
Hello @FluffyDiscord.

I'd like to check this issue only happens with PackingInfiniteGrid, or in all Grids.
Do you encounter same problem when using this implementation on other Grid types?

**Comment by FluffyDiscord** [comment] 2022-11-07 07:26
Every grid has its issues, but the packing one is the worst offender. I have switched to css grid masonry since this package also had big issues with that.

**Comment by malangfox** [comment] 2022-11-09 03:25
I'm guessing this issue is that the text overflows out of the div when `word-break: break-all` is not applied.
I made a [demo](https://codesandbox.io/s/infinitegrid-overflow-vcqhcn?file=/App.svelte) about this, and when I delete the `word-break` in css, a scroll bar is created inside certain items.
This means that the text of the item is overflowing like the issue you left.

Could this issue can be solved by applying `word-break` or `overflow-x` css?

**Comment by FluffyDiscord** [comment] 2022-11-09 08:22
If you look at your example, text gets cut off. Same issue as I have, but the other way around.

![image](https://user-images.githubusercontent.com/10332247/200776761-cb14b91a-2b43-45f1-951d-4d9212178513.png)

**Comment by daybrush** [comment] 2022-11-24 07:15
@FluffyDiscord 

Hello ~

There are some problems with combining items.

`display: flex` seems to be the cause of breaking the proportions of the image.
Also, it seems to be a problem because it failed to maintain the ratio and the size of the text area is not constant.
The sizeRange is set larger than the size of the text area (100).


Check out the following demo.
https://codesandbox.io/s/infinitegrid-overflow-forked-qce48p?file=/App.svelte

**Comment by FluffyDiscord** [comment] 2022-11-24 07:38
The text size needs to be dynamic, just as image size is.

Your fork also looks broken

![Screenshot_20221124_083523_Yuzu Browser](https://user-images.githubusercontent.com/10332247/203721570-be0fca8b-f1d2-48a7-94cc-9387ce000b5f.jpg)

**Comment by daybrush** [comment] 2022-11-24 07:48
@FluffyDiscord 

The phenomenon that items are broken when the screen size is very small (maybe less 400) will be fixed in the next version.

**Comment by daybrush** [comment] 2022-11-24 09:12
@FluffyDiscord 

I have a few questions

1. Is the width different for each item?
2. Is the height different for each item?
3. Can you tell me what kind of structure layout you want?


The img's width seems to be fixed.

**Comment by FluffyDiscord** [comment] 2022-11-24 10:09
1. - 2. Both width and height might be different for each item, but I am not strictly setting the width or height.

3. I would like to have the PackingInfiniteGrid layout.

**Comment by malangfox** [comment] 2022-12-30 03:24
@FluffyDiscord 

Sorry for the delay in checking and replying.
Currently, it seems difficult for the Grid component to implement the layout you left in the comment.
If we can support the layout example you left through future updates, we will leave you a comment.

**Closed** 2022-12-30 08:48 UTC
Labels: svelte
